### ISSUE TITLE
CLONE_NEWPID is not a valid Linux::Unshare macro

### ISSUE THREAD

**Issue by camtauxe** [hackman/Linux-Unshare#7]
After importing all of the clone flags (`use Linux::Unshare qw(unshare :clone);`) attempting to access the CLONE_NEWPID constant croaks with error in the title (`CLONE_NEWPID is not a valid Linux::Unshare macro`).

**To reproduce**
`perl -MLinux::Unshare="unshare,:clone" -e 'unshare(CLONE_NEWPID)'`

This is happening on Linux Kernel version **5.4.0-7634-generic**. I know I have access to the CLONE_NEWPID flag in sched.h, because I have written other programs that use it.

**Comment by hackman** [comment]
This is now fixed in version 1.2.
